version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express-api-template
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "8886:3306" # Change external port to 9091
    volumes:
      - mysql_data:/var/lib/mysql
      - ./express-api-template.sql:/docker-entrypoint-initdb.d/express-api-template.sql  # Mount SQL file

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root      # Default MySQL user
      PMA_PASSWORD: root  # Password for the PMA_USER
    ports:
      - "8887:80"

volumes:
  mysql_data:
