version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: express-api-template
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "8886:3306"
    volumes:
      - ./mysql-docker:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: root      
      PMA_PASSWORD: root 
    ports:
      - "8887:80"

volumes:
  mysql-docker:
    driver: local
